# Generated by Django 3.0.8 on 2020-09-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
